'''file contains region and departement dict'''

departements = {
    'Toute la France/Régions':[
    "Tous les départements", 
    "Ain", 
    "Aisne", 
    "Allier",
    "Alpes-de-Haute-Provence",
    "Hautes-Alpes",
    "Alpes-Maritimes",
    "Ardèche",
    "Ardennes",
    "Ariège",
    "Aube",
    "Aude",
    "Aveyron",
    "Bouches-du-Rhône",
    "Calvados",
    "Cantal",
    "Charente",
    "Charente-Maritime",
    "Cher",
    "Corrèze",
    "Corse-du-Sud",
    "Haute-Corse",
    "Côte-d'Or",
    "Côtes d'Armor",
    "Creuse",
    "Dordogne",
    "Doubs",
    "Drôme",
    "Eure",
    "Eure-et-Loir",
    "Finistère",
    "Gard",
    "Haute-Garonne",
    "Gers",
    "Gironde",
    "Hérault",
    "Ille-et-Vilaine",
    "Indre",
    "Indre-et-Loire",
    "Isère",
    "Jura",
    "Landes",
    "Loir-et-Cher",
    "Loire",
    "Haute-Loire",
    "Loire-Atlantique",
    "Loiret",
    "Lot",
    "Lot-et-Garonne",
    "Lozère",
    "Maine-et-Loire",
    "Manche",
    "Marne",
    "Haute-Marne",
    "Mayenne",
    "Meurthe-et-Moselle",
    "Meuse",
    "Morbihan",
    "Moselle",
    "Nièvre",
    "Nord",
    "Oise",
    "Orne",
    "Pas-de-Calais",
    "Puy-de-Dôme",
    "Pyrénées-Atlantiques",
    "Hautes-Pyrénées",
    "Pyrénées-Orientales",
    "Bas-Rhin",
    "Haut-Rhin",
    "Rhône",
    "Haute-Saône",
    "Saône-et-Loire",
    "Sarthe",
    "Savoie",
    "Haute-Savoie",
    "Paris",
    "Seine-Maritime",
    "Seine-et-Marne",
    "Yvelines",
    "Deux-Sèvres",
    "Somme",
    "Tarn",
    "Tarn-et-Garonne",
    "Var",
    "Vaucluse",
    "Vendée",
    "Vienne",
    "Haute-Vienne",
    "Vosges",
    "Yonne",
    "Territoire de Belfort",
    "Essonne",
    "Hauts-de-Seine",
    "Seine-St-Denis",
    "Val-de-Marne",
    "Val-D'Oise",
    "Guadeloupe",
    "Martinique",
    "Guyane",
    "La Réunion",
    "Mayotte"
    ],
    'Auvergne-Rhônes-Alpes':[
    "Tous les départements",
    "Ain",
    "Allier",
    "Ardèche",
    "Cantal",
    "Drôme",
    "Haute-Loire",
    "Haute-Savoie",
    "Isère",
    "Loire",
    "Puy-de-Dôme",
    "Rhône",
    "Savoie"
    ],
    'Bourgogne-Franche-Comté':[
    "Tous les départements",
    "Côte-d'Or",
    "Doubs",
    "Haute-Saône",
    "Jura",
    "Nièvre",
    "Saône-et-Loire",
    "Territoire de Belfort",
    "Yonne"
    ],
    'Bretagne':[
    "Tous les départements",
    "Côtes d'Armor",
    "Finistère",
    "Ille-et-Vilaine",
    "Morbihan"
    ],
    'Centre-Val de Loire':[
    "Tous les départements",
    "Cher",
    "Eure-et-Loir",
    "Indre",
    "Indre-et-Loire",
    "Loir-et-Cher",
    "Loiret"
    ],
    'Corse':[
    "Tous les départements",
    "Corse-du-Sud",
    "Haute-Corse"
    ],
    'Grand Est':[
    "Tous les départements",
    "Ardennes",
    "Aube",
    "Bas-Rhin",
    "Haut-Rhin",
    "Haute-Marne",
    "Marne",
    "Meurthe-et-Moselle",
    "Meuse",
    "Moselle",
    "Vosges"
    ],
    'Guadeloupe':[
    "Tous les départements",
    "Guadeloupe"
    ],
    'Guyanne':[
    "Tous les départements",
    "Guyane",
    ],
    'Hauts-de-France':[
    "Tous les départements",
    "Aisne",
    "Nord",
    "Oise",
    "Pas-de-Calais",
    "Somme"
    ],
    'Ile-de-France':[
    "Tous les départements",
    "Essonne",
    "Hauts-de-Seine",
    "Paris",
    "Seine-et-Marne",
    "Seine-St-Denis",
    "Val-D'Oise",
    "Val-de-Marne",
    "Yvelines"
    ],
    'Martinique':[
    "Tous les départements",
    "Martinique"
    ],
    'Mayotte':[
    "Tous les départements",
    "Mayotte"
    ],
    'Normandie':[
    "Tous les départements",
    "Calvados",
    "Eure",
    "Manche",
    "Orne",
    "Seine-Maritime"
    ],
    'Nouvelle-Aquitaine':[
    "Tous les départements",
    "Charente",
    "Charente-Maritime",
    "Corrèze",
    "Creuse",
    "Deux-Sèvres",
    "Dordogne",
    "Gironde",
    "Haute-Vienne",
    "Landes",
    "Lot-et-Garonne",
    "Pyrénées-Atlantiques",
    "Vienne"
    ],
    'Occitanie':[
    "Tous les départements",
    "Ariège",
    "Aude",
    "Aveyron",
    "Gard",
    "Gers",
    "Haute-Garonne",
    "Hautes-Pyrénées",
    "Hérault",
    "Lot",
    "Lozère",
    "Pyrénées-Orientales",
    "Tarn",
    "Tarn-et-Garonne"
    ],
    'Pays de la Loire':[
    "Tous les départements",
    "Loire-Atlantique",
    "Maine-et-Loire",
    "Mayenne",
    "Sarthe",
    "Vendée"
    ],
    "Provence-Alpes-Côte d'Azur":[
    "Tous les départements",
    "Alpes-de-Haute-Provence",
    "Alpes-Maritimes",
    "Bouches-du-Rhône",
    "Hautes-Alpes",
    "Var",
    "Vaucluse"
    ],
    'Réunion':[
    "Tous les départements",
    "La Réunion"
    ]
}
