"""file contains region and departement dict"""

departements = {
    "Toute la France/Régions": [
        "Tous les départements",
        "Ain",
        "Aisne",
        "Allier",
        "Alpes-de-Haute-Provence",
        "Hautes-Alpes",
        "Alpes-Maritimes",
        "Ardèche",
        "Ardennes",
        "Ariège",
        "Aube",
        "Aude",
        "Aveyron",
        "Bouches-du-Rhône",
        "Calvados",
        "Cantal",
        "Charente",
        "Charente-Maritime",
        "Cher",
        "Corrèze",
        "Corse-du-Sud",
        "Haute-Corse",
        "Côte-d'Or",
        "Côtes d'Armor",
        "Creuse",
        "Dordogne",
        "Doubs",
        "Drôme",
        "Eure",
        "Eure-et-Loir",
        "Finistère",
        "Gard",
        "Haute-Garonne",
        "Gers",
        "Gironde",
        "Hérault",
        "Ille-et-Vilaine",
        "Indre",
        "Indre-et-Loire",
        "Isère",
        "Jura",
        "Landes",
        "Loir-et-Cher",
        "Loire",
        "Haute-Loire",
        "Loire-Atlantique",
        "Loiret",
        "Lot",
        "Lot-et-Garonne",
        "Lozère",
        "Maine-et-Loire",
        "Manche",
        "Marne",
        "Haute-Marne",
        "Mayenne",
        "Meurthe-et-Moselle",
        "Meuse",
        "Morbihan",
        "Moselle",
        "Nièvre",
        "Nord",
        "Oise",
        "Orne",
        "Pas-de-Calais",
        "Puy-de-Dôme",
        "Pyrénées-Atlantiques",
        "Hautes-Pyrénées",
        "Pyrénées-Orientales",
        "Bas-Rhin",
        "Haut-Rhin",
        "Rhône",
        "Haute-Saône",
        "Saône-et-Loire",
        "Sarthe",
        "Savoie",
        "Haute-Savoie",
        "Paris",
        "Seine-Maritime",
        "Seine-et-Marne",
        "Yvelines",
        "Deux-Sèvres",
        "Somme",
        "Tarn",
        "Tarn-et-Garonne",
        "Var",
        "Vaucluse",
        "Vendée",
        "Vienne",
        "Haute-Vienne",
        "Vosges",
        "Yonne",
        "Territoire de Belfort",
        "Essonne",
        "Hauts-de-Seine",
        "Seine-St-Denis",
        "Val-de-Marne",
        "Val-D'Oise",
        "Guadeloupe",
        "Martinique",
        "Guyane",
        "La Réunion",
        "Mayotte",
    ],
    "Auvergne-Rhônes-Alpes": [
        "Tous les départements",
        "Ain",
        "Allier",
        "Ardèche",
        "Cantal",
        "Drôme",
        "Haute-Loire",
        "Haute-Savoie",
        "Isère",
        "Loire",
        "Puy-de-Dôme",
        "Rhône",
        "Savoie",
    ],
    "Bourgogne-Franche-Comté": [
        "Tous les départements",
        "Côte-d'Or",
        "Doubs",
        "Haute-Saône",
        "Jura",
        "Nièvre",
        "Saône-et-Loire",
        "Territoire de Belfort",
        "Yonne",
    ],
    "Bretagne": [
        "Tous les départements",
        "Côtes d'Armor",
        "Finistère",
        "Ille-et-Vilaine",
        "Morbihan",
    ],
    "Centre-Val de Loire": [
        "Tous les départements",
        "Cher",
        "Eure-et-Loir",
        "Indre",
        "Indre-et-Loire",
        "Loir-et-Cher",
        "Loiret",
    ],
    "Corse": ["Tous les départements", "Corse-du-Sud", "Haute-Corse"],
    "Grand Est": [
        "Tous les départements",
        "Ardennes",
        "Aube",
        "Bas-Rhin",
        "Haut-Rhin",
        "Haute-Marne",
        "Marne",
        "Meurthe-et-Moselle",
        "Meuse",
        "Moselle",
        "Vosges",
    ],
    "Guadeloupe": ["Tous les départements", "Guadeloupe"],
    "Guyanne": [
        "Tous les départements",
        "Guyane",
    ],
    "Hauts-de-France": [
        "Tous les départements",
        "Aisne",
        "Nord",
        "Oise",
        "Pas-de-Calais",
        "Somme",
    ],
    "Ile-de-France": [
        "Tous les départements",
        "Essonne",
        "Hauts-de-Seine",
        "Paris",
        "Seine-et-Marne",
        "Seine-St-Denis",
        "Val-D'Oise",
        "Val-de-Marne",
        "Yvelines",
    ],
    "Martinique": ["Tous les départements", "Martinique"],
    "Mayotte": ["Tous les départements", "Mayotte"],
    "Normandie": [
        "Tous les départements",
        "Calvados",
        "Eure",
        "Manche",
        "Orne",
        "Seine-Maritime",
    ],
    "Nouvelle-Aquitaine": [
        "Tous les départements",
        "Charente",
        "Charente-Maritime",
        "Corrèze",
        "Creuse",
        "Deux-Sèvres",
        "Dordogne",
        "Gironde",
        "Haute-Vienne",
        "Landes",
        "Lot-et-Garonne",
        "Pyrénées-Atlantiques",
        "Vienne",
    ],
    "Occitanie": [
        "Tous les départements",
        "Ariège",
        "Aude",
        "Aveyron",
        "Gard",
        "Gers",
        "Haute-Garonne",
        "Hautes-Pyrénées",
        "Hérault",
        "Lot",
        "Lozère",
        "Pyrénées-Orientales",
        "Tarn",
        "Tarn-et-Garonne",
    ],
    "Pays de la Loire": [
        "Tous les départements",
        "Loire-Atlantique",
        "Maine-et-Loire",
        "Mayenne",
        "Sarthe",
        "Vendée",
    ],
    "Provence-Alpes-Côte d'Azur": [
        "Tous les départements",
        "Alpes-de-Haute-Provence",
        "Alpes-Maritimes",
        "Bouches-du-Rhône",
        "Hautes-Alpes",
        "Var",
        "Vaucluse",
    ],
    "Réunion": ["Tous les départements", "La Réunion"],
}


departements_number = {
        "Ain":"01",
        "Aisne":"02",
        "Allier":"03",
        "Alpes-de-Haute-Provence":"04",
        "Hautes-Alpes":"05",
        "Alpes-Maritimes":"06",
        "Ardèche":"07",
        "Ardennes":"08",
        "Ariège":"09",
        "Aube":"10",
        "Aude":"11",
        "Aveyron":"12",
        "Bouches-du-Rhône":"13",
        "Calvados":"14",
        "Cantal":"15",
        "Charente":"16",
        "Charente-Maritime":"17",
        "Cher":"18",
        "Corrèze":"19",
        "Corse-du-Sud":"20",
        "Haute-Corse":"20",
        "Côte-d'Or":"21",
        "Côtes d'Armor":"22",
        "Creuse":"23",
        "Dordogne":"24",
        "Doubs":"25",
        "Drôme":"26",
        "Eure":"27",
        "Eure-et-Loir":"28",
        "Finistère":"29",
        "Gard":"30",
        "Haute-Garonne":"31",
        "Gers":"32",
        "Gironde":"33",
        "Hérault":"34",
        "Ille-et-Vilaine":"35",
        "Indre":"36",
        "Indre-et-Loire":"37",
        "Isère":"38",
        "Jura":"39",
        "Landes":"40",
        "Loir-et-Cher":"41",
        "Loire":"42",
        "Haute-Loire":"43",
        "Loire-Atlantique":"44",
        "Loiret":"45",
        "Lot":"46",
        "Lot-et-Garonne":"47",
        "Lozère":"48",
        "Maine-et-Loire":"49",
        "Manche":"50",
        "Marne":"51",
        "Haute-Marne":"52",
        "Mayenne":"53",
        "Meurthe-et-Moselle":"54",
        "Meuse":"55",
        "Morbihan":"56",
        "Moselle":"57",
        "Nièvre":"58",
        "Nord":"59",
        "Oise":"60",
        "Orne":"61",
        "Pas-de-Calais":"62",
        "Puy-de-Dôme":"63",
        "Pyrénées-Atlantiques":"64",
        "Hautes-Pyrénées":"65",
        "Pyrénées-Orientales":"66",
        "Bas-Rhin":"67",
        "Haut-Rhin":"68",
        "Rhône":"69",
        "Haute-Saône":"70",
        "Saône-et-Loire":"71",
        "Sarthe":"72",
        "Savoie":"73",
        "Haute-Savoie":"74",
        "Paris":"75",
        "Seine-Maritime":"76",
        "Seine-et-Marne":"77",
        "Yvelines":"78",
        "Deux-Sèvres":"79",
        "Somme":"80",
        "Tarn":"81",
        "Tarn-et-Garonne":"82",
        "Var":"83",
        "Vaucluse":"84",
        "Vendée":"85",
        "Vienne":"86",
        "Haute-Vienne":"87",
        "Vosges":"88",
        "Yonne":"89",
        "Territoire de Belfort":"90",
        "Essonne":"91",
        "Hauts-de-Seine":"92",
        "Seine-St-Denis":"93",
        "Val-de-Marne":"94",
        "Val-D'Oise":"95",
        "Guadeloupe":"971",
        "Martinique":"972",
        "Guyane":"973",
        "La Réunion":"974",
        "Mayotte":"976",
}
