# Generated by Django 3.1.7 on 2021-04-05 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_ad_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proposed_services', models.ManyToManyField(null=True, related_name='proposed_services', to=settings.AUTH_USER_MODEL)),
                ('required_services', models.ManyToManyField(null=True, related_name='required_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
