# Generated by Django 3.1.7 on 2021-04-05 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_category_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='proposed_services',
            field=models.ManyToManyField(related_name='proposed_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='required_services',
            field=models.ManyToManyField(related_name='required_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
