# Generated by Django 3.1.7 on 2021-04-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_auto_20210406_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
