# Generated by Django 3.1.7 on 2021-06-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_user_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment_pending',
        ),
    ]
