# Generated by Django 3.1.7 on 2021-04-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
