# Generated by Django 3.1.7 on 2021-04-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210402_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
